title: Guilherme
description: Meus Estudos de DotNET

url: https://github.com/arkanael/arkanael.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Início
   url: /index.html
 - title: Sobre
   url: /about
 - title: Contato
   url: /contact

social:
   github: arkanael
   twitter: arkanael
   facebook: luiz.guilherme.58367
   email: arkanael@gmail.com

google_analytics: ""
